orgs:
  aicoe-aiops:
    admins:
      - 4n4nd
      - durandom
      - goern
      - harshad16
      - MichaelClifford
      - sesheta
      - tumido
    billing_email: mhild@redhat.com
    company: ""
    default_repository_permission: read
    description: ""
    email: ""
    has_organization_projects: true
    has_repository_projects: false
    location: ""
    members:
      - aakankshaduggal
      - adberglund
      - amsaparov
      - anishasthana
      - antter
      - cdolfi
      - chambridge
      - chargio
      - chauhankaranraj
      - dccurtis
      - hemajv
      - HumairAK
      - ilya-kolchinsky
      - iNecas
      - isabelizimm
      - janzeleny
      - kholdaway
      - margarethaley
      - martinpovolny
      - mbacovsky
      - oindrillac
      - SankBad
      - Shreyanand
      - subpop
      - suppathak
      - xiormeesh
      - radekvokal
      - mklika
      - falox
      - smarterclayton
      - nstielau
      - joshuawilson
      - ri-dubey
      - dgpatelgit
      - nicolekay2
    members_can_create_repositories: false
    name: ""
    repos:
      ai-enablement-initiative:
        description:
          This is to keep track of issues and documentation regarding the AI
          enablement initiative
        has_projects: false
        private: true
      auto-faq:
        description: use mailing list data to auto generate FAQ's
        has_projects: false
        private: true
      categorical-encoding:
        description:
          Encoding schemes for nominal categorical variables in an unsupervised
          setting.
        has_projects: false
      categorical-encoding-internal:
        has_projects: false
        private: true
      ceph-data-drive-failure:
        has_projects: false
        private: true
      ceph_drive_failure:
        description:
          An AI/ML solution that provides a probability that a hard drive will
          fail within some pre-defined time period.
        has_projects: false
        has_wiki: false
      cja-topic-modeling:
        has_projects: false
        private: true
      cloud-price-analysis:
        has_projects: false
        private: true
      cloud-price-analysis-public:
        has_projects: false
      common:
        default_branch: main
        has_projects: false
      configuration-files-analysis:
        description: Misconfiguration detection in configuration files
        has_projects: false
      cpaas-automated-failure-analysis:
        description: "cpaas-automated-failure-analysis "
        has_projects: false
        private: true
      data-science-workflow-examples:
        has_projects: false
      data-science-workflows:
        has_projects: false
        has_wiki: false
      disk-health-predictor:
        has_projects: false
        has_wiki: false
      fedora-mailing-list-analysis:
        description:
          "This will be the repo for the Fedora mailing list sentiment analysis
          project "
        has_projects: false
      flake-qe:
        has_projects: false
      github-labeler:
        has_projects: false
      insights-configuration-files-analysis:
        description: analysis and rule generation for configuration files.
        has_projects: false
        private: true
      insights-drift-analysis-baselines:
        has_projects: false
        private: true
      insights-grokket:
        description:
          "Syncing Insights with Grokket fingerprints and other meta-data available
          for consumption. "
        has_projects: false
        private: true
      insights-invocation-hints:
        has_projects: false
        private: true
      insights-sap-analysis:
        description:
          In this project, we analyze SAP instances on customer systems using
          data collected from Insights.
        has_projects: false
        private: true
      mailing-list-analysis-toolkit:
        description: "Opensource mailing list analysis with open data hub "
        has_projects: false
      ocp-alert-prediction:
        has_projects: false
        private: true
      ocp-alert-prediction-public:
        has_projects: false
      ocp-ci-analysis:
        has_projects: false
      ocp4-anomaly-detection-internal:
        description: Anomaly Detection in OCP4 deployments
        has_projects: false
        private: true
      openshift-anomaly-detection:
        has_projects: false
      openshift-sme-mailing-list-analysis:
        description: openshift-sme-mailing-list-analysis
        has_projects: false
        private: true
      openshift-workload-fingerprinting:
        description:
          Analyze and fingerprint workloads running on OpenShift to gain insights
          into customer usage patterns,and to drive business decisions.
        has_projects: false
        private: true
      operate-first-openshift-data:
        description:
          "Example data and EDA for metrics, logs and events generated by the
          operate first OpenShift Environment "
        has_projects: false
        private: true
      performance-qe:
        has_projects: false
        private: true
      pet-image-detection:
        default_branch: main
        has_projects: false
      project-template:
        description:
          this is a template to use for new data science projects in the aiops
          group
        has_projects: false
      ri-optimization:
        has_projects: false
        private: true
      sentiment-analysis-demo:
        has_projects: false
        private: true
      sentiment-analysis-public:
        has_projects: false
      sync-pipelines:
        description: Solgate home repo. Event-driven kubernetes native S3 sync toolkit
        has_projects: false
      sync-pipelines-private:
        has_projects: false
        private: true
      time-series:
        description: A repository showing example analysis of time series data.
        has_projects: false
      vulnerability-analysis:
        description:
          Project around automating the process of mapping from an upstream
          security announcement to a set of affected components inside products and their
          versions by using AI methods and tools.
        has_projects: false
        private: true
    teams:
      Red Hat:
        description: For non AICoE Red Hatters who would like access to this org
        maintainers:
          - MichaelClifford
        members:
          - subpop
          - iNecas
          - mbacovsky
          - adberglund
          - hemajv
          - chargio
          - janzeleny
          - xiormeesh
          - chambridge
          - kholdaway
          - ilya-kolchinsky
          - radekvokal
          - mklika
          - falox
          - smarterclayton
          - nstielau
          - joshuawilson
          - ri-dubey
          - dgpatelgit
          - nicolekay2
        privacy: closed
        repos:
          ceph_drive_failure: read
          cloud-price-analysis: triage
          disk-health-predictor: read
          insights-invocation-hints: triage
          ocp-alert-prediction: triage
          openshift-workload-fingerprinting: triage
      SourceOps:
        description: "This is our SourceOps team, they keep the source fresh."
        maintainers:
          - sesheta
        privacy: closed
        repos:
          ai-enablement-initiative: admin
          auto-faq: admin
          categorical-encoding: admin
          categorical-encoding-internal: admin
          ceph-data-drive-failure: admin
          ceph_drive_failure: admin
          cja-topic-modeling: admin
          cloud-price-analysis: admin
          cloud-price-analysis-public: admin
          configuration-files-analysis: admin
          cpaas-automated-failure-analysis: admin
          data-science-workflow-examples: admin
          data-science-workflows: admin
          disk-health-predictor: admin
          fedora-mailing-list-analysis: admin
          flake-qe: admin
          github-labeler: admin
          insights-configuration-files-analysis: admin
          insights-drift-analysis-baselines: admin
          insights-grokket: admin
          insights-invocation-hints: admin
          insights-sap-analysis: admin
          mailing-list-analysis-toolkit: admin
          ocp-alert-prediction: admin
          ocp-alert-prediction-public: admin
          ocp-ci-analysis: admin
          ocp4-anomaly-detection-internal: admin
          openshift-anomaly-detection: admin
          openshift-sme-mailing-list-analysis: admin
          openshift-workload-fingerprinting: admin
          operate-first-openshift-data: admin
          performance-qe: admin
          pet-image-detection: admin
          project-template: admin
          ri-optimization: admin
          sentiment-analysis-demo: admin
          sentiment-analysis-public: admin
          sync-pipelines: admin
          sync-pipelines-private: admin
          time-series: admin
          vulnerability-analysis: admin
      team-aiops:
        description: All members of the AIOps team in the AICoE
        maintainers:
          - durandom
          - MichaelClifford
          - tumido
          - 4n4nd
        members:
          - martinpovolny
          - hemajv
          - Shreyanand
          - HumairAK
          - chauhankaranraj
          - aakankshaduggal
          - suppathak
          - oindrillac
          - isabelizimm
          - antter
          - amsaparov
          - margarethaley
        privacy: closed
        repos:
          ai-enablement-initiative: triage
          auto-faq: triage
          categorical-encoding: triage
          categorical-encoding-internal: triage
          ceph-data-drive-failure: triage
          ceph_drive_failure: triage
          cja-topic-modeling: triage
          cloud-price-analysis: triage
          cloud-price-analysis-public: triage
          configuration-files-analysis: triage
          data-science-workflow-examples: triage
          data-science-workflows: triage
          disk-health-predictor: triage
          fedora-mailing-list-analysis: triage
          flake-qe: triage
          insights-configuration-files-analysis: triage
          insights-drift-analysis-baselines: triage
          insights-grokket: triage
          insights-invocation-hints: triage
          insights-sap-analysis: triage
          mailing-list-analysis-toolkit: triage
          ocp-alert-prediction: triage
          ocp-alert-prediction-public: triage
          ocp-ci-analysis: triage
          ocp4-anomaly-detection-internal: triage
          openshift-anomaly-detection: triage
          openshift-sme-mailing-list-analysis: triage
          operate-first-openshift-data: triage
          performance-qe: triage
          pet-image-detection: triage
          project-template: triage
          ri-optimization: triage
          sentiment-analysis-demo: triage
          sentiment-analysis-public: triage
          sync-pipelines: triage
          sync-pipelines-private: triage
          time-series: triage
          vulnerability-analysis: triage
